### PR TITLE
Use custom JSX implementation of GitHub's markdown toolbar that works in IE

### LINKED ISSUE #1671: [Markdown] Tabbing out of post composer does not work
The new Markdown toolbar has introduced new keyboard shortcuts to the post composer. 

Unfortunately, one of these overrides the tabindex function, making a TAB insert 4 spaces at the beginning of the cursor's current line. 

Now that you've recovered from the shock of a tab using spaces, I'll remind you that a tab from the composer window **should** trigger the tabindex function of the DOM and move the cursor out of the composer window and to the Post/submit button.

### LINKED ISSUE #1679: [Markdown] Toolbar missing image button
On Beta 8's new toolbar for Markdown, there is no image button to insert `alt text` code.

### LINKED ISSUE #1702: [Markdown] Toolbar causes issues in IE 11
## Bug Report

**Current Behavior**
In Internet Explorer Version 11 (11.407.17134.0) on Windows 10 (10.0.17134 Build 17134), I am unable to create a discussion or even reply to one when I am logged in. What makes this absolutely weird is that I'm getting no errors in the console and the only reason how I came across these bugs was that I was in the process of retesting to #1174. I can reproduce this both locally and on Flarum Discuss (despite Flarum Discuss running on dev-master). I have kept in mind that Microsoft does not support this browser anymore as of January 12, 2016, but it is still bundled with the OS and is still widely used with legacy web applications.

**Steps to Reproduce**

Part 1:
1. Open up Internet Explorer (Version 11).
2. Go to your locally hosted Flarum or https://discuss.flarum.org/
3. Log in if you aren't already.
4. Click on the "Start a Discussion button".
5. Observe as the discussion composer does not appear.

Part 2: 
1. Open up Internet Explorer (Version 11).
2. Go to your locally hosted Flarum or  https://discuss.flarum.org/
3. Log in if you aren't already.
4. Open up any discussion that is not locked.
5. Attempt to reply to the discussion.
6. Observe as the reply/pos composer does not appear.

**Expected Behavior**
In using IE11, I should be able to create a new discussion and see the discussion composer pop-up as well as being able to reply to any discussion that is not locked.

**Screenshots**
N/A

**Environment**
- Flarum version: v0.1.0-beta.8.1 (locally hosted) or dev-master on Flarum Discuss
- Website URL: Localhost or https://discuss.flarum.org/
- Webserver: Apache (locally hosted)
- Hosting environment: Locally hosted (WAMP)
- PHP version: 7.2.4 (locally hosted)
- Browser: Internet Explorer Version 11 (11.407.17134.0)

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

```
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.4
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, jso
n, mcrypt, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenize
r, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter,
 openssl, curl, fileinfo, gd, gettext, gmp, intl, imap, ldap, mbstring, exif, my
sqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, xmlrpc, xsl
+----------------------+-----------------+--------+
| Flarum Extensions    |                 |        |
+----------------------+-----------------+--------+
| ID                   | Version         | Commit |
+----------------------+-----------------+--------+
| flarum-approval      | v0.1.0-beta.8   |        |
| flarum-bbcode        | v0.1.0-beta.8   |        |
| flarum-emoji         | v0.1.0-beta.8   |        |
| flarum-lang-english  | v0.1.0-beta.8   |        |
| flarum-flags         | v0.1.0-beta.8.1 |        |
| flarum-likes         | v0.1.0-beta.8.1 |        |
| flarum-lock          | v0.1.0-beta.8   |        |
| flarum-markdown      | v0.1.0-beta.8   |        |
| flarum-mentions      | v0.1.0-beta.8.1 |        |
| flarum-statistics    | v0.1.0-beta.8   |        |
| flarum-sticky        | v0.1.0-beta.8   |        |
| flarum-subscriptions | v0.1.0-beta.8   |        |
| flarum-suspend       | v0.1.0-beta.8   |        |
| flarum-tags          | v0.1.0-beta.8.2 |        |
+----------------------+-----------------+--------+
Base URL: http://b81.test
Installation path: C:\wamp64\www\b81.test
Debug mode: off
```

**Possible Solution**
N/A

**Additional Context**
N/A

### PR DESCRIPTION
**Pull request by dsevillamartin**
Fixes flarum/core#1702.
Fixes flarum/core#1671.
Fixes flarum/core#1679.

image

- Created `MarkdownToolbar` and `MarkdownButton` elements
    - Replacement for custom HTML elements
- Brought the textarea logic from `@github/markdown-toolbar-element` into flarum/markdown
    - Wasn't sure how we would want the file structure, I separated the functions into 3 different files
    - Modified some code so that it works in IE, two functions needed pollyfill
        - `String#startsWith`, `String#endsWith`
- Buttons that support hotkeys now have the proper meta key in the tooltip
    - macOS: `⌘`
    - other: `ctrl`

---

- Do we want to have the styles or button configurations stored somewhere else ?
- We'll probably need to somehow include the [LICENSE](https://github.com/github/markdown-toolbar-element/blob/master/LICENSE) as a bunch of code was copied and modified from there.
    - Perhaps in those comments that don't disappear when compiling. Something like this ?

       ```js
       /*!
        * Includes modified code from GitHub Markdown Toolbar Element
        * https://github.com/github/markdown-toolbar-element/
        * 
        * Original Copyright GitHub, Inc.
        * Released under the MIT license
        * https://github.com/github/markdown-toolbar-element/blob/master/LICENSE
        *
        * Date: 2019-07-10T16:37Z
        */
       ```

### CODE REVIEW

File: js/src/forum/index.js [hunk 1]
```diff
@@ -1,17 +1,12 @@
...
+import MarkdownArea from 'mdarea';
 
-let MarkdownArea;
-
-if (window.Reflect) {
-  require('@webcomponents/custom-elements');
-  require('@github/markdown-toolbar-element');
-  MarkdownArea = require('mdarea/mdarea.js');
-}
+import './pollyfills';
```
Comment (franzliedke) [inline js/src/forum/index.js]: Me thinks this should be `polyfills`. :smile:

File: js/src/forum/pollyfills.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
+if (!String.prototype.startsWith) {
+  Object.defineProperty(String.prototype, 'startsWith', {
+    value: function(search, pos) {
+      pos = !pos || pos < 0 ? 0 : +pos;
+      return this.substring(pos, pos + search.length) === search;
+    }
+  });
+}
```
Comment (franzliedke) [inline js/src/forum/pollyfills.js]: Where are these taken from? Any other licenses we need to mention?

File: js/src/forum/util/apply.js [hunk 3]
```diff
@@ -0,0 +1,45 @@
+import insertText from './insertText';
+import {blockStyle, isMultipleLines, multilineStyle, orderedList} from "./styles";
```
Comment (franzliedke) [inline js/src/forum/util/apply.js]: I smell inconsistent quotes. :scream:

**Review by franzliedke — CHANGES_REQUESTED** [review]
Awesome, nice job!!!

Yes, we definitely need to mention GitHub's license as well. I'd say we definitely need to add the following line to our `LICENSE` file:

    based on code Copyright (c) 2017-2018 GitHub, Inc.

I am unsure about the rules for bundled and minified JS code. Does that need to include license information as well? Especially if the code, like ours, is available open-source...

File: js/src/forum/pollyfills.js (hunk 2 above)
Comment (dsevillamartin) [reply js/src/forum/pollyfills.js]: These are taken from the MDN polyfils @ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill & https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#Polyfill.

However, it looks like they first is taken from https://github.com/mathiasbynens/String.prototype.startsWith, so perhaps we want to use the NPM packages instead to avoid licensing issues. Upon further look though, the code from it is way more complicated compared to these 8 lines

Looks like simply including `/*! https://mths.be/startswith v0.2.0 by @mathias */` above it might be sufficient.

File: js/src/forum/index.js (hunk 1 above)
Comment (dsevillamartin) [reply js/src/forum/index.js]: 🙈

File: js/src/forum/util/apply.js (hunk 3 above)
Comment (dsevillamartin) [reply js/src/forum/util/apply.js]: 🙈

**Comment by dsevillamartin** [comment]
@franzliedke To include the license in the dist file, one uses `/*!` as compilers do not remove comments declared with `/*!`.

I'm not sure if what I wrote would suffice. We could most likely simplify it (and probably should, to reduce bundle size), following one of the examples found @ [Open source licensing notices in Web Applications](https://www.ifosslr.org/index.php/ifosslr/article/view/47/102).

Most likely use the following format, though only with the `!` once instead of 3 times (once for each file, as I separated the code to make it (hopefully) more readable).

```js
/*!
 * Copyright OWNER NAME. Licensed under NAME LICENSE HERE
 * See license text at http://example.com/license
 */
```

so use something like

```js
/*!
 * Original Copyright GitHub, Inc. Licensed under the MIT License.
 * See license text at https://github.com/github/markdown-toolbar-element/blob/master/LICENSE.
 */
```

Example with the `String.prototype.startsWith` polyfill:
image

**Comment by dsevillamartin** [comment]
We might want to consider bringing the base implementation into core. That way, other extensions can add buttons for things like BBCode without having flarum/markdown enabled.

Thoughts ?

**Comment by luceos** [comment]
@datitisev can we update/create an issue so that we keep track of that?

**Comment by franzliedke** [comment]
Why was this merged without a single copyright notice?

**Comment by dsevillamartin** [comment]
@franzliedke Oh, I thought I had taken care of it, and mentioned so in the meeting. 

The following should be fine (add to all 3 files that use Github code, but only one should use `/*!`, the rest just `/*`)
```js
/*!
 * Original Copyright GitHub, Inc. Licensed under the MIT License.
 * See license text at https://github.com/github/markdown-toolbar-element/blob/master/LICENSE.
 */
```

**Comment by franzliedke** [comment]
Yes, please add that in master.

**Comment by dsevillamartin** [comment]
I had to add it to `index.js` because, for some reason, webpack only keeps comments starting with `/*!` (or maybe any comment) from the root level... ? Any comment that I put in the `js/src/forum/utils` folder gets deleted... not sure why.

Also added the line to LICENSE.
